BoVoyage/BoVoyage/Models/Voyage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BoVoyage.Models
{
    public partial class Voyage
    {
        public Voyage()
        {
            Dossierresa = new HashSet<Dossierresa>();
            Voyageur = new HashSet<Voyageur>();
        }
        [Display(Name = "IdVoyage")]
        public int Id { get; set; }

        [Display(Name = "IdDestination")]
        [Required(ErrorMessage = "Champ requis.")]
        public int IdDestination { get; set; }

        [DataType(DataType.Date), Display(Name = "Date de départ")]
        [Required(ErrorMessage = "Champ requis.")]
        public DateTime DateDepart { get; set; }

        [DataType(DataType.Date), Display(Name = "Date de retour")]
        [Required(ErrorMessage = "Champ requis.")]
        public DateTime DateRetour { get; set; }

        [Display(Name = "Nombre de places disponibles")]
        [Required(ErrorMessage = "Champ requis.")]
        public int PlacesDispo { get; set; }

        [Display(Name = "Prix HT"),DataType(DataType.Currency)]
        [Required(ErrorMessage = "Champ requis.")]
        public decimal PrixHt { get; set; }

        [Display(Name = "Taux de réduction")]
        [Range(0.0, 1.0, ErrorMessage ="Veuillez entrer un nombre entre 0 et 1.")]
        [Required(ErrorMessage = "Champ requis.")]
        public decimal Reduction { get; set; }

        [Display(Name = "Descriptif du voyage")]
        public string Descriptif { get; set; }

        [Display(Name ="Destination")]
        public virtual Destination IdDestinationNavigation { get; set; }
        public virtual ICollection<Dossierresa> Dossierresa { get; set; }
        public virtual ICollection<Voyageur> Voyageur { get; set; }
    }
}

BoVoyage/BoVoyage/Areas/Client/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoVoyage.Areas.Client.Models;
using BoVoyage.Models;
using BoVoyage.Controllers;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace BoVoyage.Areas.Client.Controllers
{
    [Area("Client")]
    [Authorize(Roles = "Member")]
    public class ReservationController : Controller
    {
        private readonly BoVoyageContext _context;

        public ReservationController(BoVoyageContext context)
        {
            _context = context;
        }

        // GET: Client/Reservation
        public async Task<IActionResult> Index(int idVoyage, int nbPersonnes)
        {
            //Gestion si la personne a déjà réservé le voyage
            var userMail = User.FindFirstValue(ClaimTypes.Name);
            var personne = await _context.Personne
                .Where(p => p.Email == userMail).Include(p => p.Client).ThenInclude(c => c.Dossierresa)
                .FirstOrDefaultAsync();
            if (personne.Client != null && personne.Client.Dossierresa.Where(d => d.IdVoyage == idVoyage).Any())
            {
                return RedirectToAction("Details", "Personnes");
            }


            var voyage = await _context.Voyage.Where(v => v.Id == idVoyage).Include(v => v.IdDestinationNavigation).FirstOrDefaultAsync();

            //Prix de base pour l'utilisateur 
            double prixTva = (double)voyage.PrixHt;

            //On s'assure que la liste de voyageur en session est déjà instancié
            List<Personne> voyageurs = HttpContext.Session.Get<List<Personne>>("voyageurs") == null ? new List<Personne>() : HttpContext.Session.Get<List<Personne>>("voyageurs");

            List<double> prixParVoyageur = PrixParVoyageur((double)voyage.PrixHt, voyageurs);

            if (nbPersonnes > voyageurs.Count())
            {
                voyageurs.Add(new Personne());
            }

            foreach (var item in prixParVoyageur)
            {
                prixTva += item;

            }
            prixTva += prixTva * 0.20;
            HttpContext.Session.Set("voyageurs", voyageurs);
            ViewBag.Utilisateur = await _context.Personne.Where(p => p.Email == User.FindFirstValue(ClaimTypes.Name)).FirstOrDefaultAsync();
            ViewBag.PrixParVoyageur = prixParVoyageur;
            HttpContext.Session.Set("prix", prixTva);
            ViewBag.PrixTva = prixTva;
            HttpContext.Session.Set("idVoyage", idVoyage);
            var voyagePersonnes = new VoyagePersonnesViewModel(voyage, voyageurs);

            return View(voyagePersonnes);
        }

        public async Task<IActionResult> AjoutVoyageur(VoyagePersonnesViewModel voyagePersonnes, int idVoyage, int nbPersonnes)
        {
            //On récupère le voyage en cours
            var voyage = _context.Voyage.Where(v => v.Id == idVoyage).Include(v => v.IdDestinationNavigation).FirstOrDefault();
            voyagePersonnes.Voyage = voyage;

            //On récupère l'utilisateur
            ViewBag.Utilisateur = _context.Personne.Where(p => p.Id == 4).FirstOrDefault();

            //Prix de base pour l'utilisateur 
            double prixTva = (double)voyage.PrixHt;

            List<double> prixParVoyageur = PrixParVoyageur((double)voyage.PrixHt, voyagePersonnes.Voyageurs);

            foreach (var item in prixParVoyageur)
            {
                prixTva += item;
            }
            prixTva += prixTva * 0.20;
            ViewBag.PrixParVoyageur = prixParVoyageur;
            ViewBag.Utilisateur = await _context.Personne.Where(p => p.Email == User.FindFirstValue(ClaimTypes.Name)).FirstOrDefaultAsync();
            ViewBag.PrixTva = prixTva;
            HttpContext.Session.Set("prix", prixTva);
            if (ModelState.IsValid)
            {
                //On stock en session si le voyageur est valide
                HttpContext.Session.Set("voyageurs", voyagePersonnes.Voyageurs);
                return RedirectToAction(nameof(Index), new { idVoyage, nbPersonnes });
            }
            return View("Index", voyagePersonnes);
        }

        public IActionResult SupprimerVoyageur(int idVoyageur, int idVoyage, int nbPersonnes)
        {

            var voyageurs = HttpContext.Session.Get<List<Personne>>("voyageurs");
            voyageurs.RemoveAt(idVoyageur);
            HttpContext.Session.Set("voyageurs", voyageurs);
            return RedirectToAction(nameof(Index), new { idVoyage, nbPersonnes = nbPersonnes - 1 });
        }

        public IActionResult Paiement()
        {
            double prix = HttpContext.Session.Get<double>("prix");
            ViewBag.Prix = prix;
            return View();
        }


        public List<double> PrixParVoyageur(double prixVoyage, List<Personne> voyageurs)
        {
            List<double> prixParVoyageur = new List<double>();

            foreach (var item in voyageurs)
            {
                if (ModelState.IsValid)
                {

                    //Reduc de 60% pour - 12ans
                    if (item.Datenaissance > DateTime.Now.AddYears(-12))
                    {
                        prixParVoyageur.Add(prixVoyage * 0.4);
                    }
                    else
                    {
                        prixParVoyageur.Add(prixVoyage);
                    }
                }
            }
            return prixParVoyageur;
        }

        public async Task<IActionResult> ValiderResa(Dossierresa dossierresa)
        {
            if (ModelState.IsValid)
            {
                var personne = await _context.Personne.Where(p => p.Email == User.FindFirstValue(ClaimTypes.Name)).FirstOrDefaultAsync();
                if (personne.TypePers == 4)
                {
                    personne.TypePers = 1;
                    _context.Client.Add(new BoVoyage.Models.Client() { Id = personne.Id });
                }

                foreach (var voyageur in HttpContext.Session.Get<List<Personne>>("voyageurs"))
                {
                    if (voyageur.Nom != null)
                    {

                        if (!_context.Personne.Where(p => p.Email == voyageur.Email).Any())
                        {
                            voyageur.TypePers = 2;
                            _context.Personne.Add(voyageur);
                        }
                        await _context.SaveChangesAsync();
                        _context.Voyageur.Add(new Voyageur() { Id = voyageur.Id, Idvoyage = HttpContext.Session.Get<int>("idVoyage") });
                    }
                }
                _context.Voyageur.Add(new Voyageur() { Id = personne.Id, Idvoyage = HttpContext.Session.Get<int>("idVoyage") });
                var dossier = new Dossierresa() { NumeroCb = dossierresa.NumeroCb, IdClient = personne.Id, IdEtatDossier = 2, IdVoyage = HttpContext.Session.Get<int>("idVoyage"), PrixTotal = HttpContext.Session.Get<decimal>("prix") };
                _context.Personne.Update(personne);
                _context.Dossierresa.Add(dossier);
                var voyage = await _context.Voyage.FindAsync(HttpContext.Session.Get<int>("idVoyage"));
                voyage.PlacesDispo = voyage.PlacesDispo - (HttpContext.Session.Get<List<Personne>>("voyageurs").Count() + 1);
                _context.Voyage.Update(voyage);
                await _context.SaveChangesAsync();
                return View();
            }
            ViewBag.Prix = HttpContext.Session.Get<double>("prix");
            return View("Paiement", dossierresa);
        }
    }
}

BoVoyage/BoVoyage/Areas/Client/Controllers/VoyagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoVoyage.Models;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.AspNetCore.Authorization;

namespace BoVoyage.Areas.Client.Controllers
{
    [Area("Client")]
    public class VoyagesController : Controller
    {
        private readonly BoVoyageContext _context;

        public VoyagesController(BoVoyageContext context)
        {
            _context = context;
        }

        // GET: Client/Voyages
        public async Task<IActionResult> Index(int? dest, decimal prixMin, decimal prixMax,DateTime dateMin, DateTime dateMax)
        {
            var listeDestinations = await _context.Destination.ToListAsync();
            ViewBag.Destinations = new SelectList(listeDestinations, "Id", "Nom",dest);
            ViewBag.PrixMin = prixMin;
            ViewBag.PrixMax = prixMax;
            
            IQueryable<Voyage> voyages = _context.Voyage.Include(v => v.IdDestinationNavigation).ThenInclude(d => d.Photo);
            
            if (dest != null && dest!=0)
                voyages = voyages.Where(v => v.IdDestinationNavigation.Id == dest);
            if (prixMin != 0 && prixMax == 0)
                voyages = voyages.Where(v => v.PrixHt >= prixMin);
            if (prixMin == 0 && prixMax != 0)
                voyages = voyages.Where(v => v.PrixHt <= prixMax);
            if (prixMin != 0 && prixMax != 0)
                voyages =  voyages.Where(v => v.PrixHt >= prixMin && v.PrixHt <= prixMax);
            if (dateMin != DateTime.MinValue && dateMax == DateTime.MinValue)
            {
                ViewBag.DateMin = dateMin.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart >= dateMin);
            }
            if (dateMin == DateTime.MinValue && dateMax != DateTime.MinValue)
            {
                ViewBag.DateMax = dateMax.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart <= dateMax);
            }
            if (dateMin != DateTime.MinValue && dateMax != DateTime.MinValue)
            {
                ViewBag.DateMin = dateMin.ToString("yyyy-MM-dd");
                ViewBag.DateMax = dateMax.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart >= dateMin && v.DateDepart <= dateMax);
            }


            var listeVoyages = await voyages.ToListAsync();            

            return View(listeVoyages);
        }

        // GET: Client/Voyages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound("Le voyage demandé ne se trouve pas dans notre base de données.");
            }

            var voyage = await _context.Voyage
                .Include(v => v.IdDestinationNavigation).ThenInclude(d => d.Photo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voyage == null)
            {
                return NotFound("Le voyage demandé ne se trouve pas dans notre base de données.");
            }

            return View(voyage);
        }      
    }
}

BoVoyage/BoVoyage/Areas/Client/Views/Voyages/Details.cshtml
@model BoVoyage.Models.Voyage

@{
    ViewData["Title"] = "Notre Voyage";
}

<h1 class="text-center mb-3">@Model.IdDestinationNavigation.Nom</h1>

<div class="row justify-content-center">
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                <p>
                    Partez en voyage du <strong>@Html.DisplayFor(modelItem => Model.DateDepart) </strong>
                    au <strong>@Html.DisplayFor(modelItem => Model.DateRetour) </strong>
                </p>
            </div>
            <div class="card-body">
                <h5 class="card-title">Votre Destination</h5>

                <p>@Model.IdDestinationNavigation.Description</p>

                <h5 class="card-title">Votre Voyage</h5>
                <p>@Model.Descriptif </p>
                <p>
                    Bénéficiez d'une réduction minimum de <strong>@((int)(Model.Reduction * 100))%</strong> par rapport au prix d'agence.
                    Transport et hébergement tout compris pour la somme de <strong>@Html.DisplayFor(modelItem => Model.PrixHt)</strong> (HT) par personne!
                </p>
                <p>Réservez vite! Il ne reste plus que <strong>@Model.PlacesDispo places disponibles!</strong> </p>
            </div>
            <div class="card-footer d-flex justify-content-center">
                <a asp-action="Index" asp-controller="Voyages" class="btn btn-primary mr-3"> Précédent </a>
                <a asp-action="Index" asp-controller="Reservation" asp-route-idVoyage="@Model.Id" class="btn btn-success ml-3"> Je réserve maintenant!</a><br />
            </div>
        </div>
    </div>
</div>
<div>
    
    
    
</div>

BoVoyage/BoVoyage/Areas/Client/Views/Voyages/Index.cshtml
@model IEnumerable<BoVoyage.Models.Voyage>

@{
    ViewData["Title"] = "Nos Voyages";
}
<div class="row mb-3">
    <div class="col-12">
        <h1 class="text-center">Nos Voyages</h1>
    </div>
</div>


<div class="row justify-content-center">
    <div class="col-md-9 mb-3">
        <div class="card">
            <div class="card-body">

                <form asp-controller="Voyages" asp-action="Index" method="get">
                    <label>Destination</label>
                    <div>
                        <select class="form-control" name="dest" asp-items="@ViewBag.Destinations">
                            <option value="0" selected>Toutes</option>
                        </select>
                    </div>

                    <div class="form-row mt-3">
                        <div class="form-group col">
                            <h6>Fourchette de prix</h6>
                            <div class="input-group mb-1">
                                <label class="col-sm-2 col-form-label">De</label>
                                <input class="form-control" name="prixMin" min="0" placeholder="Prix Min" value="@ViewBag.PrixMin" />
                                <div class="input-group-append">
                                    <span class="input-group-text">€</span>
                                </div>
                            </div>
                            <div class="input-group mb-1">
                                <label class="col-sm-2 col-form-label">A</label>
                                <input class="form-control" name="prixMax" min="0" placeholder="Prix Max" value="@ViewBag.PrixMax" />
                                <div class="input-group-append">
                                    <span class="input-group-text">€</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col">
                            <h6>Fourchette de date de départ</h6>
                            <div class="input-group mb-1">
                                <label class="col-sm-2 col-form-label">Du</label>
                                <input class="form-control" type="date" name="dateMin" value="@ViewBag.DateMin" />
                            </div>
                            <div class="input-group mb-1">
                                <label class="col-sm-2 col-form-label">Au</label>
                                <input class="form-control" type="date" name="dateMax" value="@ViewBag.DateMax" />
                            </div>
                        </div>
                    </div>
                    <div class="form-group d-flex justify-content-center">

                        <button class="btn btn-primary mr-3" type="submit">Filtrer</button>
                        <a class="btn btn-primary ml-3" asp-action="Index"> Effacer filtre </a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="col-md-11">
        <div class="card-columns">

            @foreach (var voyage in Model)

            {
                @if (voyage.PlacesDispo != 0)
                {<div class="card">
                        @if (!voyage.IdDestinationNavigation.Photo.Any())
                        {
                            <img src="~/img/no_result.jpg" class="card-img-top" alt="@Html.DisplayFor(modelItem => voyage.IdDestinationNavigation.Nom)">
                        }
                        else
                        {
                            <img src="/img/@voyage.IdDestinationNavigation.Photo.First().NomFichier" class="card-img-top" alt="@Html.DisplayFor(modelItem => voyage.IdDestinationNavigation.Nom)">

                        }
                        <div class="card-body">
                            <h3 class="card-title">@Html.DisplayFor(modelItem => voyage.IdDestinationNavigation.Nom)</h3>
                            <p class="card-text">
                                Du <strong>@Html.DisplayFor(modelItem => voyage.DateDepart) </strong>
                                au <strong>@Html.DisplayFor(modelItem => voyage.DateRetour) </strong>
                            </p>
                            <p>@Html.DisplayFor(modelItem => voyage.Descriptif)</p>
                            <div class="d-flex justify-content-center">

                                <a asp-action="Details" asp-route-id="@voyage.Id" class="btn btn-secondary">En savoir plus</a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <p class="text-center">Au prix de <span class="font-weight-bold">@Html.DisplayFor(modelItem => voyage.PrixHt)</span>/personne</p>
                        </div>
                    </div>}

            }
        </div>

    </div>

    @if (!Model.Any())
    {<p>Désolé. Aucun voyage ne correspond à votre recherche.</p>}
</div>