BoVoyage/BoVoyage/Areas/Client/Controllers/PersonnesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoVoyage.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using BoVoyage.Data;

namespace BoVoyage.Areas.Client.Controllers
{
    [Area("Client")]
    public class PersonnesController : Controller
    {
        private readonly BoVoyageContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _contextApp;
        private readonly SignInManager<IdentityUser> _signInManager;

        public PersonnesController(BoVoyageContext context, UserManager<IdentityUser> userManager, ApplicationDbContext contextApp,SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _contextApp = contextApp;
            _signInManager = signInManager;
        }

        // GET: Client/Personnes/Details/5
        public async Task<IActionResult> Details()
        {
            var userMail = User.FindFirstValue(ClaimTypes.Name);
            if (userMail == null)
            {
                return NotFound();
            }

            IQueryable<Personne> pers = _context.Personne.Include(p => p.Client).ThenInclude(c => c.Dossierresa).ThenInclude(d => d.IdEtatDossierNavigation)
                                                          .Include(p=>p.Client).ThenInclude(c=>c.Dossierresa).ThenInclude(d=>d.IdVoyageNavigation).ThenInclude(v=>v.IdDestinationNavigation);

            var personne = await pers
                
                .Where(p => p.Email == userMail)
                .FirstOrDefaultAsync();


            if (personne == null)
            {
                return NotFound();
            }

            return View(personne);
        }

        // GET: Client/Personnes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Client/Personnes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TypePers,Civilite,Nom,Prenom,Email,Telephone,Datenaissance")] Personne personne)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personne);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personne);
        }

        // GET: Client/Personnes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personne = await _context.Personne.FindAsync(id);
            if (personne == null)
            {
                return NotFound();
            }
            return View(personne);
        }

        // POST: Client/Personnes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TypePers,Civilite,Nom,Prenom,Email,Telephone,Datenaissance")] Personne personne)
        {
            if (id != personne.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personne);
                    await _context.SaveChangesAsync();
                    var user = await _contextApp.Users.Where(u=>u.Email==User.FindFirstValue(ClaimTypes.Name)).SingleOrDefaultAsync();
                    user.Email = personne.Email;
                    user.UserName = personne.Email;
                    user.PhoneNumber = personne.Telephone;
                    await _userManager.UpdateAsync(user);
                    await _signInManager.SignInAsync(user, true);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonneExists(personne.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details");
            }
            return View(personne);
        }

        private bool PersonneExists(int id)
        {
            return _context.Personne.Any(e => e.Id == id);
        }
    }
}

BoVoyage/BoVoyage/Areas/Client/Controllers/VoyagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoVoyage.Models;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.AspNetCore.Authorization;

namespace BoVoyage.Areas.Client.Controllers
{
    [Area("Client")]
    public class VoyagesController : Controller
    {
        private readonly BoVoyageContext _context;

        public VoyagesController(BoVoyageContext context)
        {
            _context = context;
        }

        // GET: Client/Voyages
        public async Task<IActionResult> Index(int? dest, decimal prixMin, decimal prixMax,DateTime dateMin, DateTime dateMax)
        {
            var listeDestinations = await _context.Destination.ToListAsync();
            ViewBag.Destinations = new SelectList(listeDestinations, "Id", "Nom",dest);
            ViewBag.PrixMin = prixMin;
            ViewBag.PrixMax = prixMax;
            
            IQueryable<Voyage> voyages = _context.Voyage.Include(v => v.IdDestinationNavigation).ThenInclude(d => d.Photo);
            
            if (dest != null && dest!=0)
                voyages = voyages.Where(v => v.IdDestinationNavigation.Id == dest);
            if (prixMin != 0 && prixMax == 0)
                voyages = voyages.Where(v => v.PrixHt >= prixMin);
            if (prixMin == 0 && prixMax != 0)
                voyages = voyages.Where(v => v.PrixHt <= prixMax);
            if (prixMin != 0 && prixMax != 0)
                voyages =  voyages.Where(v => v.PrixHt >= prixMin && v.PrixHt <= prixMax);
            if (dateMin != DateTime.MinValue && dateMax == DateTime.MinValue)
            {
                ViewBag.DateMin = dateMin.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart >= dateMin);
            }
            if (dateMin == DateTime.MinValue && dateMax != DateTime.MinValue)
            {
                ViewBag.DateMax = dateMax.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart <= dateMax);
            }
            if (dateMin != DateTime.MinValue && dateMax != DateTime.MinValue)
            {
                ViewBag.DateMin = dateMin.ToString("yyyy-MM-dd");
                ViewBag.DateMax = dateMax.ToString("yyyy-MM-dd");
                voyages = voyages.Where(v => v.DateDepart >= dateMin && v.DateDepart <= dateMax);
            }


            var listeVoyages = await voyages.ToListAsync();            

            return View(listeVoyages);
        }

        // GET: Client/Voyages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound("Le voyage demandé ne se trouve pas dans notre base de données.");
            }

            var voyage = await _context.Voyage
                .Include(v => v.IdDestinationNavigation).ThenInclude(d => d.Photo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voyage == null)
            {
                return NotFound("Le voyage demandé ne se trouve pas dans notre base de données.");
            }

            return View(voyage);
        }      
    }
}

BoVoyage/BoVoyage/Areas/Office/Controllers/ManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BoVoyage.Areas.Office.Models;
using BoVoyage.Models;
using BoVoyage.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace BoVoyage.Areas.Office.Controllers
{
    [Area("Office")]
    [Authorize(Roles = "Admin")]
    public class ManagersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ManagersController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Office/Managers
        public async Task<IActionResult> Index()
        {
            var users = await _context.Users.ToListAsync();
            Dictionary<string, string> roles = new Dictionary<string, string>();
            foreach(var user in users)
            {
                var s = "";
                foreach (var role in await _userManager.GetRolesAsync(user))
                    s += " "+role;
                roles.Add(user.Id,s);
            }
            ViewBag.Roles = roles;
            return View(users);
        }

        // GET: Office/Managers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manager == null)
            {
                return NotFound();
            }
            string role = "";
            foreach (var roles in await _userManager.GetRolesAsync(manager))
                role += "" + roles;
            ViewBag.Roles = role;
            return View(manager);
        }

        // GET: Office/Managers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Office/Managers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhoneNumber,Email,Password")] Manager manager)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = manager.Email, Email = manager.Email, PhoneNumber = manager.PhoneNumber, EmailConfirmed = true };
                var result = await _userManager.CreateAsync(user, manager.Password);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "Manager");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manager);
        }

        // GET: Office/Managers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Users.FindAsync(id);
            if (manager == null)
            {
                return NotFound();
            }
            return View(manager);
        }

        // POST: Office/Managers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,PhoneNumber,Email")] Manager manager)
        {
            if (id != manager.Id)
            {
                return NotFound();
            }
            try
            {
                var user = _context.Users.Find(id);
                user.Email = manager.Email;
                user.UserName = manager.Email;
                user.PhoneNumber = manager.PhoneNumber;
                await _userManager.UpdateAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ManagerExists(manager.Id))
                {
                    return NotFound();
                }
                else
                {
                    return View(new IdentityUser() { Id = id, Email = manager.Email, PhoneNumber = manager.PhoneNumber });
                }
            }

            
        }

        // GET: Office/Managers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // POST: Office/Managers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var manager = await _context.Users.FindAsync(id);
            await _userManager.DeleteAsync(manager);
            return RedirectToAction(nameof(Index));
        }

        private bool ManagerExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

BoVoyage/BoVoyage/Views/Shared/VoyageCard.cshtml
@model BoVoyage.Models.Voyage

@{
    string[] descriptionMinim = Model.Descriptif.Split(' ', 20);
    descriptionMinim[descriptionMinim.Length - 1] = " ...";
}
<div class="">
    <div class="card m-3">
        @if (!@Model.IdDestinationNavigation.Photo.Any())
        {
            <img src="~/img/no_result.jpg" class="card-img-top" alt="">
        }
        else
        {
            <img src="~/img/@Model.IdDestinationNavigation.Photo.First().NomFichier" class="card-img-top" alt="">

        }
        <div class="card-body">
            <h3 class="card-title">@Model.IdDestinationNavigation.Nom</h3>
            <p class="card-text">
                Du <strong>@Html.DisplayFor(modelItem => Model.DateDepart)</strong>
                au <strong>@Html.DisplayFor(modelItem => Model.DateRetour)</strong>
            </p>
            <p class="text-justify">@string.Join(' ', descriptionMinim)</p>
            <div class="d-flex justify-content-center">
                <a asp-area="Client" asp-controller="Voyages" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">En savoir plus</a>
            </div>
        </div>
        <div class="card-footer">
            <p class="text-center">Au prix de <span class="font-weight-bold">@Html.DisplayFor(modelItem => Model.PrixHt)</span>/personne</p>
        </div>
    </div>
</div>

BoVoyage/BoVoyage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoVoyage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                {
                    <a class="navbar-brand text-light" asp-area="Office" asp-controller="Dashboard" asp-action="Index">BoVoyage</a>
                }
                else
                {
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">BoVoyage</a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Dashboard" asp-action="Index">Tableau de Bord</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Destinations" asp-action="Index">Destinations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Voyages" asp-action="Index">Voyages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Dossierresas" asp-action="Index">Dossier Réservation</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Personnes" asp-action="Index">Clients</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Client" asp-controller="Voyages" asp-action="Index">Liste de voyages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="AProposDe">A propos de nous</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Office" asp-controller="Managers" asp-action="Index">Commerciaux</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <div class="row">
                <div class="col text-center font-weight-bold text-wrap height">
                    &copy; 2020 - BoVoyage - Projet GTM Ingenierie<br />
                    Florentin DEROSNE - Dorian GUILLAUME - Aurore LÊ
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>